version: '3.8'

services:
  app-blue:
    image: ghcr.io/yangsijun528/hakko:latest
    ports:
      - 8081:8080
    networks:
      - app-network
    environment:
      - ENV=blue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1

  app-green:
    image: ghcr.io/yangsijun528/hakko:latest
    ports:
      - 8082:8080
    networks:
      - app-network
    environment:
      - ENV=green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-blue
      - app-green
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
