name: Project CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_REMOTE }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/hakko
            
            # 최신 코드 가져오기
            git pull origin main
            
            # Gradle 빌드
            echo "Starting Gradle build..."
            ./gradlew clean build -x test || { echo "Gradle build failed!" >&2; exit 1; }

            # 도커 이미지 빌드
            echo "Building Docker image..."
            docker build -t hakko-app:latest .

            # 기존 컨테이너 종료 및 제거
            echo "Stopping and removing existing container..."
            docker stop hakko-app || true
            docker rm hakko-app || true

            # 새 컨테이너 실행
            echo "Starting new Docker container..."
            docker run -d --name hakko-app -p 8080:8080 hakko-app:latest

            # 컨테이너 상태 확인
            echo "Waiting for the application to start..."
            sleep 10
            if ! docker logs hakko-app | grep -q "Started"; then
              echo "Application did not start successfully." >&2
              exit 1
            fi

            echo "Application is running and healthy!"
