# 야매 CI 코드
name: Project CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/hakko
            
            # git pull로 최신 코드 가져오기
            git pull origin main
            
            # gradle을 사용해 jar 파일 빌드
            ./gradlew clean build -x test
            
            # 현재 날짜로 로그 파일명 생성
            LOG_DATE=$(date +%Y%m%d)
            LOG_DIR="../logs"
            LOG_FILE="$LOG_DIR/hakko-$LOG_DATE.log"
            
            # logs 디렉토리가 없으면 생성
            mkdir -p $LOG_DIR
            
            # hakko가 포함된 jar 프로세스 찾아서 종료
            pid=$(pgrep -f ".*hakko.*\.jar")
            if [ ! -z "$pid" ]; then
              echo "Killing process $pid"
              kill -9 $pid
              sleep 3  # 프로세스가 완전히 종료되길 기다림
            fi
            
            # build/libs 디렉토리에서 hakko로 시작하는 jar 파일 찾아서 실행
            cd build/libs
            JAR_FILE=$(ls hakko*.jar | grep -v plain.jar | head -n 1)
            
            # 백그라운드에서 실행하고 즉시 SSH 세션 종료
            nohup java -jar $JAR_FILE > $LOG_FILE 2>&1 </dev/null &
            disown
            
            # 프로세스가 시작되었는지 확인
            sleep 2
            if pgrep -f "$JAR_FILE" > /dev/null; then
              echo "New application successfully started with jar: $JAR_FILE"
              echo "Logs available at: $LOG_FILE"
            else
              echo "Failed to start application"
              exit 1
            fi
