# 야매 CI 코드
name: Project CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: execute remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_REMOTE }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/hakko
          
          # 최신 코드 가져오기
          git pull origin main
          
          # Gradle 빌드
          ./gradlew clean build -x test
          
          # 로그 디렉토리와 파일명 설정
          LOG_DATE=$(date +%Y%m%d-%H%M%S)
          LOG_DIR="../hakko-logs"
          LOG_FILE="$LOG_DIR/hakko-$LOG_DATE.log"
          mkdir -p $LOG_DIR
          
          # 기존 프로세스 종료
          pid=$(pgrep -f ".*hakko.*\.jar")
          if [ ! -z "$pid" ]; then
            echo "Killing process $pid"
            kill -9 $pid
            sleep 3
          fi
          
          # 새 애플리케이션 실행 (메모리 제한 추가)
          nohup java -Xms512m -Xmx1024m -jar ./build/libs/hakko.jar > $LOG_FILE 2>&1 &
          echo "New application started with logs at: $LOG_FILE"
