name: CD Workflow

# CD 워크플로는 CI 워크플로가 성공한 후 트리거됩니다.
on:
  workflow_run:
    workflows:
      - CI Workflow # 트리거 조건: CI Workflow 성공
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 원격 서버로 배포
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_REMOTE }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            echo "Docker 이미지를 Pull합니다..."
            docker pull hakko:latest

            echo "기존 컨테이너를 중지하고 제거합니다..."
            docker stop hakko-app || true
            docker rm hakko-app || true

            echo "새 Docker 컨테이너를 실행합니다..."
            docker run -d --name hakko-app -p 8080:8080 hakko:latest

            echo "배포가 성공적으로 완료되었습니다!"
