name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_REMOTE }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            echo "Deploy 시작..."

            # Docker 이미지 최신 Pull
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            # 현재 배포 상태 확인
            ACTIVE_SERVICE=$(docker-compose ps -q app-blue | xargs docker inspect --format '{{.State.Running}}' | grep 'true' && echo "blue" || echo "green")
            if [ "$ACTIVE_SERVICE" == "blue" ]; then
              NEW_SERVICE="green"
            else
              NEW_SERVICE="blue"
            fi

            echo "현재 활성 서비스: $ACTIVE_SERVICE"
            echo "새 서비스: $NEW_SERVICE"

            # docker-compose 업데이트
            docker-compose up -d app-$NEW_SERVICE
            docker-compose up -d nginx

            echo "Nginx 리로드 및 이전 서비스 제거..."
            docker-compose exec nginx nginx -s reload

            docker-compose stop app-$ACTIVE_SERVICE
            docker-compose rm -f app-$ACTIVE_SERVICE

            echo "무중단 배포 완료!"
