name: CI Workflow

# main 브랜치에 푸시될 때 트리거
on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. JDK 설치 및 Gradle 빌드
      - name: Set up JDK and build with Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application
        run: |
          echo "Starting Gradle build..."
          ./gradlew build -x test

      # 3. 이미지의 metadata 추출
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository_owner }}/hakko

      # 4. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # 5. QEMU 설치 (다중 아키텍처 지원)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 6. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile # Dockerfile 경로
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
